# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loijingApp', '0002_applyloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculturalloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Agricultural loan',
            },
        ),
        migrations.CreateModel(
            name='BusinessExpansionLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Business Expansion Loan',
            },
        ),
        migrations.CreateModel(
            name='EasyMonthlyInstallmentEMI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Easy Monthly Installment(EMI)',
            },
        ),
        migrations.CreateModel(
            name='EntrepreneurshipLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Entrepreneurship Loan',
            },
        ),
        migrations.CreateModel(
            name='FisheryPiggeryPoultryLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Fishery/Piggery/Poultry Loan',
            },
        ),
        migrations.CreateModel(
            name='GoldLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Gold Loan',
            },
        ),
        migrations.CreateModel(
            name='LoanAgainstProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Loan Against Property',
            },
        ),
        migrations.CreateModel(
            name='LoanReferencetoNationalizedBanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Loan Reference to Nationalized Banks',
            },
        ),
        migrations.CreateModel(
            name='MachineryLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Machinery Loan',
            },
        ),
        migrations.CreateModel(
            name='PersonalCommercialVehicleLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage (Personal/Commercial) Vehicle Loan',
            },
        ),
        migrations.CreateModel(
            name='ServicePensionloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Service/Pension loan',
            },
        ),
    ]
