# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loijingApp', '0006_companyvision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyvision',
            old_name='Companyvision',
            new_name='Companyvisioncontent',
        ),
    ]
