# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-08 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loijingApp', '0009_auto_20181207_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicableFor', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name_plural': 'Manage Form Charges Applicable',
            },
        ),
    ]
