# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-08 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loijingApp', '0010_applicable'),
    ]

    operations = [
        migrations.CreateModel(
            name='whyChooseUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us',
            },
        ),
    ]
