# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loijingApp', '0012_companymis'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryImage', models.ImageField(upload_to='galleryFiles')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
