# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 14:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loijingApp', '0017_auto_20181219_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='directorDeskTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Director Message Two',
            },
        ),
        migrations.AlterModelOptions(
            name='directordesk',
            options={'verbose_name_plural': 'Director Message One'},
        ),
    ]
