# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loijingApp', '0018_auto_20181222_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='carausalPhotoOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageCarausal', models.ImageField(upload_to='carausal')),
            ],
            options={
                'verbose_name_plural': 'Carausal Photos One',
            },
        ),
        migrations.CreateModel(
            name='carausalPhotoThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageCarausal', models.ImageField(upload_to='carausal')),
            ],
            options={
                'verbose_name_plural': 'Carausal Photos Three',
            },
        ),
        migrations.CreateModel(
            name='carausalPhotoTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageCarausal', models.ImageField(upload_to='carausal')),
            ],
            options={
                'verbose_name_plural': 'Carausal Photos Two',
            },
        ),
    ]
