# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-26 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loijingApp', '0019_carausalphotoone_carausalphotothree_carausalphototwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carausalphotoone',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carausalphotothree',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='carausalphototwo',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
