# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loijingApp', '0020_auto_20190226_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberImage', models.ImageField(upload_to='MemberOne')),
                ('memberName', models.CharField(blank=True, max_length=200, null=True)),
                ('memberPosition', models.CharField(blank=True, max_length=200, null=True)),
                ('memberDescription', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Member Three',
            },
        ),
    ]
